#!/bin/sh
cleandig host-invalid.test.dyndns ANY | sed 's/\(ahu.example.dyndns. \)\([0-9]*\)/\12012060701/'
$testname/sendupdate.pl $nameserver $port
cleandig host-invalid.test.dyndns ANY | sed 's/\(ahu.example.dyndns. \)\([0-9]*\)/\12012060701/'
