#!/bin/sh
cleandig delete-add.test.dyndns ANY
$testname/deleterecord.pl $nameserver $port
cleandig delete-add.test.dyndns ANY
$testname/addrecord.pl $nameserver $port
cleandig delete-add.test.dyndns ANY
