#!/bin/sh
cleandig test.dyndns SOA | sed 's/\(ahu.example.dyndns. \)\([0-9]*\)/\12012060701/'
$testname/replace1.pl $nameserver $port
cleandig test.dyndns SOA
$testname/replace2.pl $nameserver $port
cleandig test.dyndns SOA
$testname/replace3.pl $nameserver $port
cleandig test.dyndns SOA
