#!/bin/sh

cleandig host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig a.host.test.dyndns ANY dnssec  | egrep 'IN[[:space:]]+NSEC'
cleandig a.a.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig c.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig a.c.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig d.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'

nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
update add d.host.test.dyndns. 3600 A 127.0.0.1
send
answer
!

cleandig host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig a.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig a.a.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig c.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig a.c.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig d.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'

nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
update delete d.host.test.dyndns. 3600 A 127.0.0.1
send
answer
!

cleandig host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'
cleandig a.host.test.dyndns ANY dnssec  | egrep 'IN[[:space:]]+NSEC'
cleandig a.a.host.test.dyndns ANY dnssec  | egrep 'IN[[:space:]]+NSEC'
cleandig c.host.test.dyndns ANY dnssec  | egrep 'IN[[:space:]]+NSEC'
cleandig a.c.host.test.dyndns ANY dnssec  | egrep 'IN[[:space:]]+NSEC'
cleandig d.host.test.dyndns ANY dnssec | egrep 'IN[[:space:]]+NSEC'