#!/bin/sh

cleandig host.test.dyndns ANY dnssec
cleandig a.host.test.dyndns ANY dnssec 
cleandig a.a.host.test.dyndns ANY dnssec
cleandig c.host.test.dyndns ANY dnssec
cleandig a.c.host.test.dyndns ANY dnssec
cleandig d.host.test.dyndns ANY dnssec
cleandig e.host.test.dyndns ANY dnssec
cleandig f.host.test.dyndns ANY dnssec

nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
update add d.host.test.dyndns. 3600 A 127.0.0.1
send
answer
!

cleandig host.test.dyndns ANY dnssec
cleandig a.host.test.dyndns ANY dnssec
cleandig a.a.host.test.dyndns ANY dnssec
cleandig c.host.test.dyndns ANY dnssec
cleandig a.c.host.test.dyndns ANY dnssec
cleandig d.host.test.dyndns ANY dnssec
cleandig e.host.test.dyndns ANY dnssec
cleandig f.host.test.dyndns ANY dnssec

nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
update delete d.host.test.dyndns. 3600 A 127.0.0.1
send
answer
!

cleandig host.test.dyndns ANY dnssec
cleandig a.host.test.dyndns ANY dnssec 
cleandig a.a.host.test.dyndns ANY dnssec 
cleandig c.host.test.dyndns ANY dnssec 
cleandig a.c.host.test.dyndns ANY dnssec 
cleandig d.host.test.dyndns ANY dnssec
cleandig e.host.test.dyndns ANY dnssec
cleandig f.host.test.dyndns ANY dnssec
