#!/bin/sh -ex
rm -f ../modules/tinydnsbackend/data.sqlite3
../pdns/pdnssec --config-dir=../modules/tinydnsbackend/ create-bind-db ../modules/tinydnsbackend/data.sqlite3
for zone in $(grep zone named.conf  | cut -f2 -d\")
do
	../pdns/pdnssec --config-dir=../modules/tinydnsbackend/ secure-zone $zone 2>&1
done
